package cli

import (
	"io"

	"github.com/charmbracelet/x/vt"
)

const processWindowScrollbackLines = 2_000

// processWindowTerminal isolates the multi-window UI from the concrete
// terminal emulator. Read returns replies generated by terminal queries in the
// process output; all other methods are owned by the session event loop.
type processWindowTerminal interface {
	io.ReadWriteCloser
	Resize(columns, rows int)
	Render() string
	Cursor() (column, row int, visible bool)
}

type virtualProcessWindowTerminal struct {
	emulator      *vt.Emulator
	cursorVisible bool
}

func newProcessWindowTerminal(columns, rows int) processWindowTerminal {
	terminal := &virtualProcessWindowTerminal{cursorVisible: true}
	terminal.emulator = vt.NewEmulator(columns, rows)
	terminal.emulator.SetScrollbackSize(processWindowScrollbackLines)
	terminal.emulator.SetCallbacks(vt.Callbacks{
		CursorVisibility: func(visible bool) {
			terminal.cursorVisible = visible
		},
	})
	return terminal
}

func (t *virtualProcessWindowTerminal) Read(data []byte) (int, error) {
	return t.emulator.Read(data)
}

func (t *virtualProcessWindowTerminal) Write(data []byte) (int, error) {
	return t.emulator.Write(data)
}

func (t *virtualProcessWindowTerminal) Close() error {
	return t.emulator.Close()
}

func (t *virtualProcessWindowTerminal) Resize(columns, rows int) {
	t.emulator.Resize(columns, rows)
}

func (t *virtualProcessWindowTerminal) Render() string {
	return t.emulator.Render()
}

func (t *virtualProcessWindowTerminal) Cursor() (int, int, bool) {
	position := t.emulator.CursorPosition()
	return position.X, position.Y, t.cursorVisible
}
