// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: remote/code/v1/remote_code.proto

package codev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_FILE_TYPE_UNSPECIFIED FileType = 0
	FileType_FILE_TYPE_REGULAR     FileType = 1
	FileType_FILE_TYPE_DIRECTORY   FileType = 2
	FileType_FILE_TYPE_SYMLINK     FileType = 3
	FileType_FILE_TYPE_OTHER       FileType = 4
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FILE_TYPE_UNSPECIFIED",
		1: "FILE_TYPE_REGULAR",
		2: "FILE_TYPE_DIRECTORY",
		3: "FILE_TYPE_SYMLINK",
		4: "FILE_TYPE_OTHER",
	}
	FileType_value = map[string]int32{
		"FILE_TYPE_UNSPECIFIED": 0,
		"FILE_TYPE_REGULAR":     1,
		"FILE_TYPE_DIRECTORY":   2,
		"FILE_TYPE_SYMLINK":     3,
		"FILE_TYPE_OTHER":       4,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_code_v1_remote_code_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_remote_code_v1_remote_code_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{0}
}

type ProcessIOMode int32

const (
	ProcessIOMode_PROCESS_IO_MODE_UNSPECIFIED ProcessIOMode = 0
	ProcessIOMode_PROCESS_IO_MODE_PIPE        ProcessIOMode = 1
	ProcessIOMode_PROCESS_IO_MODE_PTY         ProcessIOMode = 2
)

// Enum value maps for ProcessIOMode.
var (
	ProcessIOMode_name = map[int32]string{
		0: "PROCESS_IO_MODE_UNSPECIFIED",
		1: "PROCESS_IO_MODE_PIPE",
		2: "PROCESS_IO_MODE_PTY",
	}
	ProcessIOMode_value = map[string]int32{
		"PROCESS_IO_MODE_UNSPECIFIED": 0,
		"PROCESS_IO_MODE_PIPE":        1,
		"PROCESS_IO_MODE_PTY":         2,
	}
)

func (x ProcessIOMode) Enum() *ProcessIOMode {
	p := new(ProcessIOMode)
	*p = x
	return p
}

func (x ProcessIOMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessIOMode) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_code_v1_remote_code_proto_enumTypes[1].Descriptor()
}

func (ProcessIOMode) Type() protoreflect.EnumType {
	return &file_remote_code_v1_remote_code_proto_enumTypes[1]
}

func (x ProcessIOMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessIOMode.Descriptor instead.
func (ProcessIOMode) EnumDescriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{1}
}

type ProcessState int32

const (
	ProcessState_PROCESS_STATE_UNSPECIFIED ProcessState = 0
	ProcessState_PROCESS_STATE_STARTING    ProcessState = 1
	ProcessState_PROCESS_STATE_RUNNING     ProcessState = 2
	ProcessState_PROCESS_STATE_EXITED      ProcessState = 3
	// The executable never started; the persistent audit record remains.
	ProcessState_PROCESS_STATE_FAILED ProcessState = 4
	// A previous controller stopped while the record was active.
	ProcessState_PROCESS_STATE_LOST ProcessState = 5
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "PROCESS_STATE_UNSPECIFIED",
		1: "PROCESS_STATE_STARTING",
		2: "PROCESS_STATE_RUNNING",
		3: "PROCESS_STATE_EXITED",
		4: "PROCESS_STATE_FAILED",
		5: "PROCESS_STATE_LOST",
	}
	ProcessState_value = map[string]int32{
		"PROCESS_STATE_UNSPECIFIED": 0,
		"PROCESS_STATE_STARTING":    1,
		"PROCESS_STATE_RUNNING":     2,
		"PROCESS_STATE_EXITED":      3,
		"PROCESS_STATE_FAILED":      4,
		"PROCESS_STATE_LOST":        5,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_code_v1_remote_code_proto_enumTypes[2].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_remote_code_v1_remote_code_proto_enumTypes[2]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessState.Descriptor instead.
func (ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{2}
}

type ProcessSignal int32

const (
	ProcessSignal_PROCESS_SIGNAL_UNSPECIFIED ProcessSignal = 0
	ProcessSignal_PROCESS_SIGNAL_HUP         ProcessSignal = 1
	ProcessSignal_PROCESS_SIGNAL_INT         ProcessSignal = 2
	ProcessSignal_PROCESS_SIGNAL_QUIT        ProcessSignal = 3
	ProcessSignal_PROCESS_SIGNAL_TERM        ProcessSignal = 4
	ProcessSignal_PROCESS_SIGNAL_KILL        ProcessSignal = 5
	ProcessSignal_PROCESS_SIGNAL_USR1        ProcessSignal = 6
	ProcessSignal_PROCESS_SIGNAL_USR2        ProcessSignal = 7
	ProcessSignal_PROCESS_SIGNAL_STOP        ProcessSignal = 8
	ProcessSignal_PROCESS_SIGNAL_CONT        ProcessSignal = 9
)

// Enum value maps for ProcessSignal.
var (
	ProcessSignal_name = map[int32]string{
		0: "PROCESS_SIGNAL_UNSPECIFIED",
		1: "PROCESS_SIGNAL_HUP",
		2: "PROCESS_SIGNAL_INT",
		3: "PROCESS_SIGNAL_QUIT",
		4: "PROCESS_SIGNAL_TERM",
		5: "PROCESS_SIGNAL_KILL",
		6: "PROCESS_SIGNAL_USR1",
		7: "PROCESS_SIGNAL_USR2",
		8: "PROCESS_SIGNAL_STOP",
		9: "PROCESS_SIGNAL_CONT",
	}
	ProcessSignal_value = map[string]int32{
		"PROCESS_SIGNAL_UNSPECIFIED": 0,
		"PROCESS_SIGNAL_HUP":         1,
		"PROCESS_SIGNAL_INT":         2,
		"PROCESS_SIGNAL_QUIT":        3,
		"PROCESS_SIGNAL_TERM":        4,
		"PROCESS_SIGNAL_KILL":        5,
		"PROCESS_SIGNAL_USR1":        6,
		"PROCESS_SIGNAL_USR2":        7,
		"PROCESS_SIGNAL_STOP":        8,
		"PROCESS_SIGNAL_CONT":        9,
	}
)

func (x ProcessSignal) Enum() *ProcessSignal {
	p := new(ProcessSignal)
	*p = x
	return p
}

func (x ProcessSignal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessSignal) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_code_v1_remote_code_proto_enumTypes[3].Descriptor()
}

func (ProcessSignal) Type() protoreflect.EnumType {
	return &file_remote_code_v1_remote_code_proto_enumTypes[3]
}

func (x ProcessSignal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessSignal.Descriptor instead.
func (ProcessSignal) EnumDescriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{3}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ControllerVersion string                 `protobuf:"bytes,1,opt,name=controller_version,json=controllerVersion,proto3" json:"controller_version,omitempty"`
	ApiVersion        string                 `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	WorkspaceName     string                 `protobuf:"bytes,3,opt,name=workspace_name,json=workspaceName,proto3" json:"workspace_name,omitempty"`
	MaxUploadBytes    int64                  `protobuf:"varint,4,opt,name=max_upload_bytes,json=maxUploadBytes,proto3" json:"max_upload_bytes,omitempty"`
	MaxProcesses      uint32                 `protobuf:"varint,6,opt,name=max_processes,json=maxProcesses,proto3" json:"max_processes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetControllerVersion() string {
	if x != nil {
		return x.ControllerVersion
	}
	return ""
}

func (x *GetInfoResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetInfoResponse) GetWorkspaceName() string {
	if x != nil {
		return x.WorkspaceName
	}
	return ""
}

func (x *GetInfoResponse) GetMaxUploadBytes() int64 {
	if x != nil {
		return x.MaxUploadBytes
	}
	return 0
}

func (x *GetInfoResponse) GetMaxProcesses() uint32 {
	if x != nil {
		return x.MaxProcesses
	}
	return 0
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          FileType               `protobuf:"varint,3,opt,name=type,proto3,enum=remote.code.v1.FileType" json:"type,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Mode          uint32                 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	SymlinkTarget string                 `protobuf:"bytes,7,opt,name=symlink_target,json=symlinkTarget,proto3" json:"symlink_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{2}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetType() FileType {
	if x != nil {
		return x.Type
	}
	return FileType_FILE_TYPE_UNSPECIFIED
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileInfo) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *FileInfo) GetSymlinkTarget() string {
	if x != nil {
		return x.SymlinkTarget
	}
	return ""
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{3}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{4}
}

func (x *StatResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

// TreeNode keeps the file hierarchy structured for non-CLI callers. Directory
// children are sorted by name; regular files and symbolic links are leaves.
type TreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Children      []*TreeNode            `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeNode) Reset() {
	*x = TreeNode{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeNode) ProtoMessage() {}

func (x *TreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeNode.ProtoReflect.Descriptor instead.
func (*TreeNode) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{7}
}

func (x *TreeNode) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *TreeNode) GetChildren() []*TreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type TreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeRequest) Reset() {
	*x = TreeRequest{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeRequest) ProtoMessage() {}

func (x *TreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeRequest.ProtoReflect.Descriptor instead.
func (*TreeRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{8}
}

func (x *TreeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type TreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *TreeNode              `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeResponse) Reset() {
	*x = TreeResponse{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeResponse) ProtoMessage() {}

func (x *TreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeResponse.ProtoReflect.Descriptor instead.
func (*TreeResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{9}
}

func (x *TreeResponse) GetRoot() *TreeNode {
	if x != nil {
		return x.Root
	}
	return nil
}

type UploadMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Overwrite     bool                   `protobuf:"varint,5,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMetadata) Reset() {
	*x = UploadMetadata{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetadata) ProtoMessage() {}

func (x *UploadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetadata.ProtoReflect.Descriptor instead.
func (*UploadMetadata) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{10}
}

func (x *UploadMetadata) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadMetadata) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *UploadMetadata) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *UploadMetadata) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadRequest_Metadata
	//	*UploadRequest_Chunk
	Payload       isUploadRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{11}
}

func (x *UploadRequest) GetPayload() isUploadRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadRequest) GetMetadata() *UploadMetadata {
	if x != nil {
		if x, ok := x.Payload.(*UploadRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadRequest_Payload interface {
	isUploadRequest_Payload()
}

type UploadRequest_Metadata struct {
	Metadata *UploadMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadRequest_Metadata) isUploadRequest_Payload() {}

func (*UploadRequest_Chunk) isUploadRequest_Payload() {}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{12}
}

func (x *UploadResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *UploadResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadResponse) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{13}
}

func (x *DownloadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DownloadMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadMetadata) Reset() {
	*x = DownloadMetadata{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMetadata) ProtoMessage() {}

func (x *DownloadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMetadata.ProtoReflect.Descriptor instead.
func (*DownloadMetadata) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{14}
}

func (x *DownloadMetadata) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type DownloadSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadSummary) Reset() {
	*x = DownloadSummary{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSummary) ProtoMessage() {}

func (x *DownloadSummary) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSummary.ProtoReflect.Descriptor instead.
func (*DownloadSummary) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{15}
}

func (x *DownloadSummary) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DownloadSummary) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

type DownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DownloadResponse_Metadata
	//	*DownloadResponse_Chunk
	//	*DownloadResponse_Summary
	Payload       isDownloadResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{16}
}

func (x *DownloadResponse) GetPayload() isDownloadResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DownloadResponse) GetMetadata() *DownloadMetadata {
	if x != nil {
		if x, ok := x.Payload.(*DownloadResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *DownloadResponse) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*DownloadResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *DownloadResponse) GetSummary() *DownloadSummary {
	if x != nil {
		if x, ok := x.Payload.(*DownloadResponse_Summary); ok {
			return x.Summary
		}
	}
	return nil
}

type isDownloadResponse_Payload interface {
	isDownloadResponse_Payload()
}

type DownloadResponse_Metadata struct {
	Metadata *DownloadMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type DownloadResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type DownloadResponse_Summary struct {
	Summary *DownloadSummary `protobuf:"bytes,3,opt,name=summary,proto3,oneof"`
}

func (*DownloadResponse_Metadata) isDownloadResponse_Payload() {}

func (*DownloadResponse_Chunk) isDownloadResponse_Payload() {}

func (*DownloadResponse_Summary) isDownloadResponse_Payload() {}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoveRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Overwrite     bool                   `protobuf:"varint,3,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{19}
}

func (x *MoveRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MoveRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *MoveRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{20}
}

func (x *MoveResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type ChmodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChmodRequest) Reset() {
	*x = ChmodRequest{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChmodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChmodRequest) ProtoMessage() {}

func (x *ChmodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChmodRequest.ProtoReflect.Descriptor instead.
func (*ChmodRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{21}
}

func (x *ChmodRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChmodRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type ChmodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChmodResponse) Reset() {
	*x = ChmodResponse{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChmodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChmodResponse) ProtoMessage() {}

func (x *ChmodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChmodResponse.ProtoReflect.Descriptor instead.
func (*ChmodResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{22}
}

func (x *ChmodResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Parents       bool                   `protobuf:"varint,3,opt,name=parents,proto3" json:"parents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{23}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MkdirRequest) GetParents() bool {
	if x != nil {
		return x.Parents
	}
	return false
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{24}
}

func (x *MkdirResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type ProcessInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pid              int64                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	IoMode           ProcessIOMode          `protobuf:"varint,4,opt,name=io_mode,json=ioMode,proto3,enum=remote.code.v1.ProcessIOMode" json:"io_mode,omitempty"`
	State            ProcessState           `protobuf:"varint,5,opt,name=state,proto3,enum=remote.code.v1.ProcessState" json:"state,omitempty"`
	Command          string                 `protobuf:"bytes,6,opt,name=command,proto3" json:"command,omitempty"`
	Arguments        []string               `protobuf:"bytes,7,rep,name=arguments,proto3" json:"arguments,omitempty"`
	WorkingDirectory string                 `protobuf:"bytes,8,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	StartedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ExitedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=exited_at,json=exitedAt,proto3" json:"exited_at,omitempty"`
	ExitCode         *int32                 `protobuf:"varint,11,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	// Native POSIX signal number when the process was terminated by a signal.
	ExitSignal *int32                 `protobuf:"varint,12,opt,name=exit_signal,json=exitSignal,proto3,oneof" json:"exit_signal,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Only names are exposed; environment values may contain secrets.
	EnvironmentKeys []string `protobuf:"bytes,14,rep,name=environment_keys,json=environmentKeys,proto3" json:"environment_keys,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{25}
}

func (x *ProcessInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetIoMode() ProcessIOMode {
	if x != nil {
		return x.IoMode
	}
	return ProcessIOMode_PROCESS_IO_MODE_UNSPECIFIED
}

func (x *ProcessInfo) GetState() ProcessState {
	if x != nil {
		return x.State
	}
	return ProcessState_PROCESS_STATE_UNSPECIFIED
}

func (x *ProcessInfo) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ProcessInfo) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ProcessInfo) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *ProcessInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ProcessInfo) GetExitedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExitedAt
	}
	return nil
}

func (x *ProcessInfo) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *ProcessInfo) GetExitSignal() int32 {
	if x != nil && x.ExitSignal != nil {
		return *x.ExitSignal
	}
	return 0
}

func (x *ProcessInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProcessInfo) GetEnvironmentKeys() []string {
	if x != nil {
		return x.EnvironmentKeys
	}
	return nil
}

type ProcessReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ProcessReference_Id
	//	*ProcessReference_Name
	//	*ProcessReference_Pid
	Value         isProcessReference_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessReference) Reset() {
	*x = ProcessReference{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessReference) ProtoMessage() {}

func (x *ProcessReference) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessReference.ProtoReflect.Descriptor instead.
func (*ProcessReference) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{26}
}

func (x *ProcessReference) GetValue() isProcessReference_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ProcessReference) GetId() string {
	if x != nil {
		if x, ok := x.Value.(*ProcessReference_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *ProcessReference) GetName() string {
	if x != nil {
		if x, ok := x.Value.(*ProcessReference_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *ProcessReference) GetPid() int64 {
	if x != nil {
		if x, ok := x.Value.(*ProcessReference_Pid); ok {
			return x.Pid
		}
	}
	return 0
}

type isProcessReference_Value interface {
	isProcessReference_Value()
}

type ProcessReference_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type ProcessReference_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

type ProcessReference_Pid struct {
	Pid int64 `protobuf:"varint,3,opt,name=pid,proto3,oneof"`
}

func (*ProcessReference_Id) isProcessReference_Value() {}

func (*ProcessReference_Name) isProcessReference_Value() {}

func (*ProcessReference_Pid) isProcessReference_Value() {}

type StartProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Concrete executable name or path. It is executed directly, without a shell.
	Command          string        `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Arguments        []string      `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	WorkingDirectory string        `protobuf:"bytes,4,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	IoMode           ProcessIOMode `protobuf:"varint,5,opt,name=io_mode,json=ioMode,proto3,enum=remote.code.v1.ProcessIOMode" json:"io_mode,omitempty"`
	// Overrides applied after inheriting the controller environment.
	Environment   map[string]string `protobuf:"bytes,6,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessRequest) Reset() {
	*x = StartProcessRequest{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessRequest) ProtoMessage() {}

func (x *StartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessRequest.ProtoReflect.Descriptor instead.
func (*StartProcessRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{27}
}

func (x *StartProcessRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartProcessRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StartProcessRequest) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *StartProcessRequest) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *StartProcessRequest) GetIoMode() ProcessIOMode {
	if x != nil {
		return x.IoMode
	}
	return ProcessIOMode_PROCESS_IO_MODE_UNSPECIFIED
}

func (x *StartProcessRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

type StartProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       *ProcessInfo           `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessResponse) Reset() {
	*x = StartProcessResponse{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse) ProtoMessage() {}

func (x *StartProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse.ProtoReflect.Descriptor instead.
func (*StartProcessResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{28}
}

func (x *StartProcessResponse) GetProcess() *ProcessInfo {
	if x != nil {
		return x.Process
	}
	return nil
}

type ListProcessesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Include exited, failed and controller-lost persistent history.
	All           bool `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesRequest) Reset() {
	*x = ListProcessesRequest{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesRequest) ProtoMessage() {}

func (x *ListProcessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesRequest.ProtoReflect.Descriptor instead.
func (*ListProcessesRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{29}
}

func (x *ListProcessesRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type ListProcessesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesResponse) Reset() {
	*x = ListProcessesResponse{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesResponse) ProtoMessage() {}

func (x *ListProcessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesResponse.ProtoReflect.Descriptor instead.
func (*ListProcessesResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{30}
}

func (x *ListProcessesResponse) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

type SignalProcessRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Process *ProcessReference      `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Signal  ProcessSignal          `protobuf:"varint,2,opt,name=signal,proto3,enum=remote.code.v1.ProcessSignal" json:"signal,omitempty"`
	// Wait for the process leader to be reaped, bounded by the RPC context.
	Wait          bool `protobuf:"varint,3,opt,name=wait,proto3" json:"wait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalProcessRequest) Reset() {
	*x = SignalProcessRequest{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalProcessRequest) ProtoMessage() {}

func (x *SignalProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalProcessRequest.ProtoReflect.Descriptor instead.
func (*SignalProcessRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{31}
}

func (x *SignalProcessRequest) GetProcess() *ProcessReference {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *SignalProcessRequest) GetSignal() ProcessSignal {
	if x != nil {
		return x.Signal
	}
	return ProcessSignal_PROCESS_SIGNAL_UNSPECIFIED
}

func (x *SignalProcessRequest) GetWait() bool {
	if x != nil {
		return x.Wait
	}
	return false
}

type SignalProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       *ProcessInfo           `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalProcessResponse) Reset() {
	*x = SignalProcessResponse{}
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalProcessResponse) ProtoMessage() {}

func (x *SignalProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_v1_remote_code_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalProcessResponse.ProtoReflect.Descriptor instead.
func (*SignalProcessResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_v1_remote_code_proto_rawDescGZIP(), []int{32}
}

func (x *SignalProcessResponse) GetProcess() *ProcessInfo {
	if x != nil {
		return x.Process
	}
	return nil
}

var File_remote_code_v1_remote_code_proto protoreflect.FileDescriptor

const file_remote_code_v1_remote_code_proto_rawDesc = "" +
	"\n" +
	" remote/code/v1/remote_code.proto\x12\x0eremote.code.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x10\n" +
	"\x0eGetInfoRequest\"\xdd\x01\n" +
	"\x0fGetInfoResponse\x12-\n" +
	"\x12controller_version\x18\x01 \x01(\tR\x11controllerVersion\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12%\n" +
	"\x0eworkspace_name\x18\x03 \x01(\tR\rworkspaceName\x12(\n" +
	"\x10max_upload_bytes\x18\x04 \x01(\x03R\x0emaxUploadBytes\x12#\n" +
	"\rmax_processes\x18\x06 \x01(\rR\fmaxProcessesJ\x04\b\x05\x10\x06\"\xec\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.remote.code.v1.FileTypeR\x04type\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\x12;\n" +
	"\vmodified_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12%\n" +
	"\x0esymlink_target\x18\a \x01(\tR\rsymlinkTarget\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"<\n" +
	"\fStatResponse\x12,\n" +
	"\x04file\x18\x01 \x01(\v2\x18.remote.code.v1.FileInfoR\x04file\"!\n" +
	"\vListRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\">\n" +
	"\fListResponse\x12.\n" +
	"\x05files\x18\x01 \x03(\v2\x18.remote.code.v1.FileInfoR\x05files\"n\n" +
	"\bTreeNode\x12,\n" +
	"\x04file\x18\x01 \x01(\v2\x18.remote.code.v1.FileInfoR\x04file\x124\n" +
	"\bchildren\x18\x02 \x03(\v2\x18.remote.code.v1.TreeNodeR\bchildren\"!\n" +
	"\vTreeRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"<\n" +
	"\fTreeResponse\x12,\n" +
	"\x04root\x18\x01 \x01(\v2\x18.remote.code.v1.TreeNodeR\x04root\"\x82\x01\n" +
	"\x0eUploadMetadata\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\fR\x06sha256\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\x1c\n" +
	"\toverwrite\x18\x05 \x01(\bR\toverwrite\"p\n" +
	"\rUploadRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.remote.code.v1.UploadMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"j\n" +
	"\x0eUploadResponse\x12,\n" +
	"\x04file\x18\x01 \x01(\v2\x18.remote.code.v1.FileInfoR\x04file\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\fR\x06sha256\"%\n" +
	"\x0fDownloadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"@\n" +
	"\x10DownloadMetadata\x12,\n" +
	"\x04file\x18\x01 \x01(\v2\x18.remote.code.v1.FileInfoR\x04file\"=\n" +
	"\x0fDownloadSummary\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\fR\x06sha256\"\xb2\x01\n" +
	"\x10DownloadResponse\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2 .remote.code.v1.DownloadMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunk\x12;\n" +
	"\asummary\x18\x03 \x01(\v2\x1f.remote.code.v1.DownloadSummaryH\x00R\asummaryB\t\n" +
	"\apayload\"A\n" +
	"\rRemoveRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"$\n" +
	"\x0eRemoveResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"e\n" +
	"\vMoveRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1c\n" +
	"\toverwrite\x18\x03 \x01(\bR\toverwrite\"<\n" +
	"\fMoveResponse\x12,\n" +
	"\x04file\x18\x01 \x01(\v2\x18.remote.code.v1.FileInfoR\x04file\"6\n" +
	"\fChmodRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\"=\n" +
	"\rChmodResponse\x12,\n" +
	"\x04file\x18\x01 \x01(\v2\x18.remote.code.v1.FileInfoR\x04file\"P\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x18\n" +
	"\aparents\x18\x03 \x01(\bR\aparents\"=\n" +
	"\rMkdirResponse\x12,\n" +
	"\x04file\x18\x01 \x01(\v2\x18.remote.code.v1.FileInfoR\x04file\"\xd4\x04\n" +
	"\vProcessInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x03R\x03pid\x126\n" +
	"\aio_mode\x18\x04 \x01(\x0e2\x1d.remote.code.v1.ProcessIOModeR\x06ioMode\x122\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1c.remote.code.v1.ProcessStateR\x05state\x12\x18\n" +
	"\acommand\x18\x06 \x01(\tR\acommand\x12\x1c\n" +
	"\targuments\x18\a \x03(\tR\targuments\x12+\n" +
	"\x11working_directory\x18\b \x01(\tR\x10workingDirectory\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x127\n" +
	"\texited_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bexitedAt\x12 \n" +
	"\texit_code\x18\v \x01(\x05H\x00R\bexitCode\x88\x01\x01\x12$\n" +
	"\vexit_signal\x18\f \x01(\x05H\x01R\n" +
	"exitSignal\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12)\n" +
	"\x10environment_keys\x18\x0e \x03(\tR\x0fenvironmentKeysB\f\n" +
	"\n" +
	"_exit_codeB\x0e\n" +
	"\f_exit_signal\"W\n" +
	"\x10ProcessReference\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x12\x12\n" +
	"\x03pid\x18\x03 \x01(\x03H\x00R\x03pidB\a\n" +
	"\x05value\"\xde\x02\n" +
	"\x13StartProcessRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1c\n" +
	"\targuments\x18\x03 \x03(\tR\targuments\x12+\n" +
	"\x11working_directory\x18\x04 \x01(\tR\x10workingDirectory\x126\n" +
	"\aio_mode\x18\x05 \x01(\x0e2\x1d.remote.code.v1.ProcessIOModeR\x06ioMode\x12V\n" +
	"\venvironment\x18\x06 \x03(\v24.remote.code.v1.StartProcessRequest.EnvironmentEntryR\venvironment\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x14StartProcessResponse\x125\n" +
	"\aprocess\x18\x01 \x01(\v2\x1b.remote.code.v1.ProcessInfoR\aprocess\"(\n" +
	"\x14ListProcessesRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\"R\n" +
	"\x15ListProcessesResponse\x129\n" +
	"\tprocesses\x18\x01 \x03(\v2\x1b.remote.code.v1.ProcessInfoR\tprocesses\"\x9d\x01\n" +
	"\x14SignalProcessRequest\x12:\n" +
	"\aprocess\x18\x01 \x01(\v2 .remote.code.v1.ProcessReferenceR\aprocess\x125\n" +
	"\x06signal\x18\x02 \x01(\x0e2\x1d.remote.code.v1.ProcessSignalR\x06signal\x12\x12\n" +
	"\x04wait\x18\x03 \x01(\bR\x04wait\"N\n" +
	"\x15SignalProcessResponse\x125\n" +
	"\aprocess\x18\x01 \x01(\v2\x1b.remote.code.v1.ProcessInfoR\aprocess*\x81\x01\n" +
	"\bFileType\x12\x19\n" +
	"\x15FILE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FILE_TYPE_REGULAR\x10\x01\x12\x17\n" +
	"\x13FILE_TYPE_DIRECTORY\x10\x02\x12\x15\n" +
	"\x11FILE_TYPE_SYMLINK\x10\x03\x12\x13\n" +
	"\x0fFILE_TYPE_OTHER\x10\x04*c\n" +
	"\rProcessIOMode\x12\x1f\n" +
	"\x1bPROCESS_IO_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROCESS_IO_MODE_PIPE\x10\x01\x12\x17\n" +
	"\x13PROCESS_IO_MODE_PTY\x10\x02*\xb0\x01\n" +
	"\fProcessState\x12\x1d\n" +
	"\x19PROCESS_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PROCESS_STATE_STARTING\x10\x01\x12\x19\n" +
	"\x15PROCESS_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14PROCESS_STATE_EXITED\x10\x03\x12\x18\n" +
	"\x14PROCESS_STATE_FAILED\x10\x04\x12\x16\n" +
	"\x12PROCESS_STATE_LOST\x10\x05*\x8e\x02\n" +
	"\rProcessSignal\x12\x1e\n" +
	"\x1aPROCESS_SIGNAL_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PROCESS_SIGNAL_HUP\x10\x01\x12\x16\n" +
	"\x12PROCESS_SIGNAL_INT\x10\x02\x12\x17\n" +
	"\x13PROCESS_SIGNAL_QUIT\x10\x03\x12\x17\n" +
	"\x13PROCESS_SIGNAL_TERM\x10\x04\x12\x17\n" +
	"\x13PROCESS_SIGNAL_KILL\x10\x05\x12\x17\n" +
	"\x13PROCESS_SIGNAL_USR1\x10\x06\x12\x17\n" +
	"\x13PROCESS_SIGNAL_USR2\x10\a\x12\x17\n" +
	"\x13PROCESS_SIGNAL_STOP\x10\b\x12\x17\n" +
	"\x13PROCESS_SIGNAL_CONT\x10\t2_\n" +
	"\x11ControllerService\x12J\n" +
	"\aGetInfo\x12\x1e.remote.code.v1.GetInfoRequest\x1a\x1f.remote.code.v1.GetInfoResponse2\x8a\x05\n" +
	"\vFileService\x12A\n" +
	"\x04Stat\x12\x1b.remote.code.v1.StatRequest\x1a\x1c.remote.code.v1.StatResponse\x12A\n" +
	"\x04List\x12\x1b.remote.code.v1.ListRequest\x1a\x1c.remote.code.v1.ListResponse\x12A\n" +
	"\x04Tree\x12\x1b.remote.code.v1.TreeRequest\x1a\x1c.remote.code.v1.TreeResponse\x12I\n" +
	"\x06Upload\x12\x1d.remote.code.v1.UploadRequest\x1a\x1e.remote.code.v1.UploadResponse(\x01\x12O\n" +
	"\bDownload\x12\x1f.remote.code.v1.DownloadRequest\x1a .remote.code.v1.DownloadResponse0\x01\x12G\n" +
	"\x06Remove\x12\x1d.remote.code.v1.RemoveRequest\x1a\x1e.remote.code.v1.RemoveResponse\x12A\n" +
	"\x04Move\x12\x1b.remote.code.v1.MoveRequest\x1a\x1c.remote.code.v1.MoveResponse\x12D\n" +
	"\x05Chmod\x12\x1c.remote.code.v1.ChmodRequest\x1a\x1d.remote.code.v1.ChmodResponse\x12D\n" +
	"\x05Mkdir\x12\x1c.remote.code.v1.MkdirRequest\x1a\x1d.remote.code.v1.MkdirResponse2\xa7\x02\n" +
	"\x0eProcessService\x12Y\n" +
	"\fStartProcess\x12#.remote.code.v1.StartProcessRequest\x1a$.remote.code.v1.StartProcessResponse\x12\\\n" +
	"\rListProcesses\x12$.remote.code.v1.ListProcessesRequest\x1a%.remote.code.v1.ListProcessesResponse\x12\\\n" +
	"\rSignalProcess\x12$.remote.code.v1.SignalProcessRequest\x1a%.remote.code.v1.SignalProcessResponseB?Z=github.com/qq1426155093/remote-code/api/remote/code/v1;codev1b\x06proto3"

var (
	file_remote_code_v1_remote_code_proto_rawDescOnce sync.Once
	file_remote_code_v1_remote_code_proto_rawDescData []byte
)

func file_remote_code_v1_remote_code_proto_rawDescGZIP() []byte {
	file_remote_code_v1_remote_code_proto_rawDescOnce.Do(func() {
		file_remote_code_v1_remote_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remote_code_v1_remote_code_proto_rawDesc), len(file_remote_code_v1_remote_code_proto_rawDesc)))
	})
	return file_remote_code_v1_remote_code_proto_rawDescData
}

var file_remote_code_v1_remote_code_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_remote_code_v1_remote_code_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_remote_code_v1_remote_code_proto_goTypes = []any{
	(FileType)(0),                 // 0: remote.code.v1.FileType
	(ProcessIOMode)(0),            // 1: remote.code.v1.ProcessIOMode
	(ProcessState)(0),             // 2: remote.code.v1.ProcessState
	(ProcessSignal)(0),            // 3: remote.code.v1.ProcessSignal
	(*GetInfoRequest)(nil),        // 4: remote.code.v1.GetInfoRequest
	(*GetInfoResponse)(nil),       // 5: remote.code.v1.GetInfoResponse
	(*FileInfo)(nil),              // 6: remote.code.v1.FileInfo
	(*StatRequest)(nil),           // 7: remote.code.v1.StatRequest
	(*StatResponse)(nil),          // 8: remote.code.v1.StatResponse
	(*ListRequest)(nil),           // 9: remote.code.v1.ListRequest
	(*ListResponse)(nil),          // 10: remote.code.v1.ListResponse
	(*TreeNode)(nil),              // 11: remote.code.v1.TreeNode
	(*TreeRequest)(nil),           // 12: remote.code.v1.TreeRequest
	(*TreeResponse)(nil),          // 13: remote.code.v1.TreeResponse
	(*UploadMetadata)(nil),        // 14: remote.code.v1.UploadMetadata
	(*UploadRequest)(nil),         // 15: remote.code.v1.UploadRequest
	(*UploadResponse)(nil),        // 16: remote.code.v1.UploadResponse
	(*DownloadRequest)(nil),       // 17: remote.code.v1.DownloadRequest
	(*DownloadMetadata)(nil),      // 18: remote.code.v1.DownloadMetadata
	(*DownloadSummary)(nil),       // 19: remote.code.v1.DownloadSummary
	(*DownloadResponse)(nil),      // 20: remote.code.v1.DownloadResponse
	(*RemoveRequest)(nil),         // 21: remote.code.v1.RemoveRequest
	(*RemoveResponse)(nil),        // 22: remote.code.v1.RemoveResponse
	(*MoveRequest)(nil),           // 23: remote.code.v1.MoveRequest
	(*MoveResponse)(nil),          // 24: remote.code.v1.MoveResponse
	(*ChmodRequest)(nil),          // 25: remote.code.v1.ChmodRequest
	(*ChmodResponse)(nil),         // 26: remote.code.v1.ChmodResponse
	(*MkdirRequest)(nil),          // 27: remote.code.v1.MkdirRequest
	(*MkdirResponse)(nil),         // 28: remote.code.v1.MkdirResponse
	(*ProcessInfo)(nil),           // 29: remote.code.v1.ProcessInfo
	(*ProcessReference)(nil),      // 30: remote.code.v1.ProcessReference
	(*StartProcessRequest)(nil),   // 31: remote.code.v1.StartProcessRequest
	(*StartProcessResponse)(nil),  // 32: remote.code.v1.StartProcessResponse
	(*ListProcessesRequest)(nil),  // 33: remote.code.v1.ListProcessesRequest
	(*ListProcessesResponse)(nil), // 34: remote.code.v1.ListProcessesResponse
	(*SignalProcessRequest)(nil),  // 35: remote.code.v1.SignalProcessRequest
	(*SignalProcessResponse)(nil), // 36: remote.code.v1.SignalProcessResponse
	nil,                           // 37: remote.code.v1.StartProcessRequest.EnvironmentEntry
	(*timestamppb.Timestamp)(nil), // 38: google.protobuf.Timestamp
}
var file_remote_code_v1_remote_code_proto_depIdxs = []int32{
	0,  // 0: remote.code.v1.FileInfo.type:type_name -> remote.code.v1.FileType
	38, // 1: remote.code.v1.FileInfo.modified_at:type_name -> google.protobuf.Timestamp
	6,  // 2: remote.code.v1.StatResponse.file:type_name -> remote.code.v1.FileInfo
	6,  // 3: remote.code.v1.ListResponse.files:type_name -> remote.code.v1.FileInfo
	6,  // 4: remote.code.v1.TreeNode.file:type_name -> remote.code.v1.FileInfo
	11, // 5: remote.code.v1.TreeNode.children:type_name -> remote.code.v1.TreeNode
	11, // 6: remote.code.v1.TreeResponse.root:type_name -> remote.code.v1.TreeNode
	14, // 7: remote.code.v1.UploadRequest.metadata:type_name -> remote.code.v1.UploadMetadata
	6,  // 8: remote.code.v1.UploadResponse.file:type_name -> remote.code.v1.FileInfo
	6,  // 9: remote.code.v1.DownloadMetadata.file:type_name -> remote.code.v1.FileInfo
	18, // 10: remote.code.v1.DownloadResponse.metadata:type_name -> remote.code.v1.DownloadMetadata
	19, // 11: remote.code.v1.DownloadResponse.summary:type_name -> remote.code.v1.DownloadSummary
	6,  // 12: remote.code.v1.MoveResponse.file:type_name -> remote.code.v1.FileInfo
	6,  // 13: remote.code.v1.ChmodResponse.file:type_name -> remote.code.v1.FileInfo
	6,  // 14: remote.code.v1.MkdirResponse.file:type_name -> remote.code.v1.FileInfo
	1,  // 15: remote.code.v1.ProcessInfo.io_mode:type_name -> remote.code.v1.ProcessIOMode
	2,  // 16: remote.code.v1.ProcessInfo.state:type_name -> remote.code.v1.ProcessState
	38, // 17: remote.code.v1.ProcessInfo.started_at:type_name -> google.protobuf.Timestamp
	38, // 18: remote.code.v1.ProcessInfo.exited_at:type_name -> google.protobuf.Timestamp
	38, // 19: remote.code.v1.ProcessInfo.created_at:type_name -> google.protobuf.Timestamp
	1,  // 20: remote.code.v1.StartProcessRequest.io_mode:type_name -> remote.code.v1.ProcessIOMode
	37, // 21: remote.code.v1.StartProcessRequest.environment:type_name -> remote.code.v1.StartProcessRequest.EnvironmentEntry
	29, // 22: remote.code.v1.StartProcessResponse.process:type_name -> remote.code.v1.ProcessInfo
	29, // 23: remote.code.v1.ListProcessesResponse.processes:type_name -> remote.code.v1.ProcessInfo
	30, // 24: remote.code.v1.SignalProcessRequest.process:type_name -> remote.code.v1.ProcessReference
	3,  // 25: remote.code.v1.SignalProcessRequest.signal:type_name -> remote.code.v1.ProcessSignal
	29, // 26: remote.code.v1.SignalProcessResponse.process:type_name -> remote.code.v1.ProcessInfo
	4,  // 27: remote.code.v1.ControllerService.GetInfo:input_type -> remote.code.v1.GetInfoRequest
	7,  // 28: remote.code.v1.FileService.Stat:input_type -> remote.code.v1.StatRequest
	9,  // 29: remote.code.v1.FileService.List:input_type -> remote.code.v1.ListRequest
	12, // 30: remote.code.v1.FileService.Tree:input_type -> remote.code.v1.TreeRequest
	15, // 31: remote.code.v1.FileService.Upload:input_type -> remote.code.v1.UploadRequest
	17, // 32: remote.code.v1.FileService.Download:input_type -> remote.code.v1.DownloadRequest
	21, // 33: remote.code.v1.FileService.Remove:input_type -> remote.code.v1.RemoveRequest
	23, // 34: remote.code.v1.FileService.Move:input_type -> remote.code.v1.MoveRequest
	25, // 35: remote.code.v1.FileService.Chmod:input_type -> remote.code.v1.ChmodRequest
	27, // 36: remote.code.v1.FileService.Mkdir:input_type -> remote.code.v1.MkdirRequest
	31, // 37: remote.code.v1.ProcessService.StartProcess:input_type -> remote.code.v1.StartProcessRequest
	33, // 38: remote.code.v1.ProcessService.ListProcesses:input_type -> remote.code.v1.ListProcessesRequest
	35, // 39: remote.code.v1.ProcessService.SignalProcess:input_type -> remote.code.v1.SignalProcessRequest
	5,  // 40: remote.code.v1.ControllerService.GetInfo:output_type -> remote.code.v1.GetInfoResponse
	8,  // 41: remote.code.v1.FileService.Stat:output_type -> remote.code.v1.StatResponse
	10, // 42: remote.code.v1.FileService.List:output_type -> remote.code.v1.ListResponse
	13, // 43: remote.code.v1.FileService.Tree:output_type -> remote.code.v1.TreeResponse
	16, // 44: remote.code.v1.FileService.Upload:output_type -> remote.code.v1.UploadResponse
	20, // 45: remote.code.v1.FileService.Download:output_type -> remote.code.v1.DownloadResponse
	22, // 46: remote.code.v1.FileService.Remove:output_type -> remote.code.v1.RemoveResponse
	24, // 47: remote.code.v1.FileService.Move:output_type -> remote.code.v1.MoveResponse
	26, // 48: remote.code.v1.FileService.Chmod:output_type -> remote.code.v1.ChmodResponse
	28, // 49: remote.code.v1.FileService.Mkdir:output_type -> remote.code.v1.MkdirResponse
	32, // 50: remote.code.v1.ProcessService.StartProcess:output_type -> remote.code.v1.StartProcessResponse
	34, // 51: remote.code.v1.ProcessService.ListProcesses:output_type -> remote.code.v1.ListProcessesResponse
	36, // 52: remote.code.v1.ProcessService.SignalProcess:output_type -> remote.code.v1.SignalProcessResponse
	40, // [40:53] is the sub-list for method output_type
	27, // [27:40] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_remote_code_v1_remote_code_proto_init() }
func file_remote_code_v1_remote_code_proto_init() {
	if File_remote_code_v1_remote_code_proto != nil {
		return
	}
	file_remote_code_v1_remote_code_proto_msgTypes[11].OneofWrappers = []any{
		(*UploadRequest_Metadata)(nil),
		(*UploadRequest_Chunk)(nil),
	}
	file_remote_code_v1_remote_code_proto_msgTypes[16].OneofWrappers = []any{
		(*DownloadResponse_Metadata)(nil),
		(*DownloadResponse_Chunk)(nil),
		(*DownloadResponse_Summary)(nil),
	}
	file_remote_code_v1_remote_code_proto_msgTypes[25].OneofWrappers = []any{}
	file_remote_code_v1_remote_code_proto_msgTypes[26].OneofWrappers = []any{
		(*ProcessReference_Id)(nil),
		(*ProcessReference_Name)(nil),
		(*ProcessReference_Pid)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remote_code_v1_remote_code_proto_rawDesc), len(file_remote_code_v1_remote_code_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_remote_code_v1_remote_code_proto_goTypes,
		DependencyIndexes: file_remote_code_v1_remote_code_proto_depIdxs,
		EnumInfos:         file_remote_code_v1_remote_code_proto_enumTypes,
		MessageInfos:      file_remote_code_v1_remote_code_proto_msgTypes,
	}.Build()
	File_remote_code_v1_remote_code_proto = out.File
	file_remote_code_v1_remote_code_proto_goTypes = nil
	file_remote_code_v1_remote_code_proto_depIdxs = nil
}
